# Generated by Django 5.2.13 on 2026-09-21 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_connexionlog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type_notification",
            field=models.CharField(
                choices=[
                    ("info", "Information"),
                    ("meeting", "Reunion"),
                    ("diplome", "Lot de diplomes"),
                    ("courrier", "Courrier"),
                    ("document", "Document"),
                ],
                default="info",
                max_length=20,
            ),
        ),
    ]
