# Generated by Django 5.2.13 on 2026-09-21 10:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Organisme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=180, unique=True)),
                (
                    "sigle",
                    models.CharField(
                        blank=True,
                        help_text="Abréviation utilisée dans le tableau de suivi, par exemple UFHB.",
                        max_length=30,
                    ),
                ),
                ("actif", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Organisme",
                "verbose_name_plural": "Organismes",
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="Bordereau",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("annee", models.PositiveIntegerField(verbose_name="Année")),
                (
                    "trimestre",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "T1"), (2, "T2"), (3, "T3"), (4, "T4")]
                    ),
                ),
                (
                    "numero",
                    models.CharField(max_length=60, verbose_name="N° de bordereau"),
                ),
                (
                    "date_reception",
                    models.DateField(
                        default=django.utils.timezone.localdate,
                        verbose_name="Date de réception",
                    ),
                ),
                (
                    "date_engagement",
                    models.DateField(
                        blank=True, null=True, verbose_name="Signature de l'engagement"
                    ),
                ),
                (
                    "date_liquidation",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Signature de la liquidation",
                    ),
                ),
                ("observation", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bordereaux_crees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organisme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bordereaux",
                        to="bordereaux.organisme",
                        verbose_name="Organisme",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bordereau",
                "verbose_name_plural": "Bordereaux",
                "ordering": ["-annee", "trimestre", "organisme__nom", "numero"],
            },
        ),
        migrations.CreateModel(
            name="BordereauHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=180)),
                ("ancien_etat", models.CharField(blank=True, max_length=30)),
                ("nouvel_etat", models.CharField(blank=True, max_length=30)),
                ("commentaire", models.TextField(blank=True)),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "bordereau",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historiques",
                        to="bordereaux.bordereau",
                    ),
                ),
                (
                    "utilisateur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bordereau_histories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Historique de bordereau",
                "verbose_name_plural": "Historiques de bordereau",
                "ordering": ["-date", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="bordereau",
            index=models.Index(fields=["annee", "trimestre"], name="bord_periode_idx"),
        ),
        migrations.AddIndex(
            model_name="bordereau",
            index=models.Index(fields=["numero"], name="bord_numero_idx"),
        ),
        migrations.AddIndex(
            model_name="bordereau",
            index=models.Index(fields=["-date_reception"], name="bord_reception_idx"),
        ),
        migrations.AddConstraint(
            model_name="bordereau",
            constraint=models.UniqueConstraint(
                fields=("organisme", "annee", "numero"),
                name="unique_numero_bordereau_par_annee",
            ),
        ),
    ]
