# Generated by Django 5.2.13 on 2026-09-21 10:42

import bordereaux.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bordereaux", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bordereau",
            options={
                "ordering": [
                    "-annee",
                    "trimestre",
                    "organisme__nom",
                    "numero",
                    "date_reception",
                ],
                "verbose_name": "Bordereau",
                "verbose_name_plural": "Bordereaux",
            },
        ),
        migrations.RemoveConstraint(
            model_name="bordereau",
            name="unique_numero_bordereau_par_annee",
        ),
        migrations.AddField(
            model_name="bordereau",
            name="fichier",
            field=models.FileField(
                blank=True,
                upload_to=bordereaux.models.bordereau_upload_path,
                verbose_name="Bordereau",
            ),
        ),
        migrations.AlterField(
            model_name="bordereau",
            name="numero",
            field=models.CharField(
                blank=True, max_length=60, verbose_name="N° de bordereau"
            ),
        ),
        migrations.AddConstraint(
            model_name="bordereau",
            constraint=models.UniqueConstraint(
                condition=models.Q(("numero", ""), _negated=True),
                fields=("organisme", "annee", "numero"),
                name="unique_numero_bordereau_par_annee",
            ),
        ),
    ]
