# Generated by Django 5.2.13 on 2026-07-10 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_service_est_service_courrier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('directeur_general', 'Directeur General'), ('secretariat', 'Secretariat'), ('administrateur', 'Administrateur'), ('responsable_service', 'Responsable service'), ('agent_simple', 'Agent simple')], default='agent_simple', max_length=32),
        ),
    ]
