# Generated by Django 5.2.13 on 2026-07-08 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_service_est_service_courrier"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Meeting",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("titre", models.CharField(max_length=180)),
                ("description", models.TextField(blank=True)),
                ("date_heure", models.DateTimeField()),
                ("salle", models.CharField(max_length=120)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("brouillon", "Brouillon"),
                            ("validee", "Validee"),
                            ("annulee", "Annulee"),
                            ("terminee", "Terminee"),
                        ],
                        default="brouillon",
                        max_length=20,
                    ),
                ),
                ("date_validation", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organisee_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="meetings_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "validee_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="meetings_validated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "membres_invites",
                    models.ManyToManyField(blank=True, related_name="meetings_invites", to=settings.AUTH_USER_MODEL),
                ),
                (
                    "services_concernes",
                    models.ManyToManyField(blank=True, related_name="meetings", to="accounts.service"),
                ),
            ],
            options={
                "verbose_name": "Reunion",
                "verbose_name_plural": "Reunions",
                "ordering": ["date_heure", "-created_at"],
            },
        ),
    ]
