# Generated by Django 5.2.13 on 2026-07-08 17:17

from django.db import migrations, models


def migrate_terminee_to_tenue(apps, schema_editor):
    Meeting = apps.get_model("meetings", "Meeting")
    Meeting.objects.filter(statut="terminee").update(statut="tenue")


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='rappel_15_envoye_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='rappel_60_envoye_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(migrate_terminee_to_tenue, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='meeting',
            name='statut',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('validee', 'Validee'), ('reportee', 'Reportee'), ('annulee', 'Annulee'), ('tenue', 'Tenue')], default='brouillon', max_length=20),
        ),
    ]
