# Generated by Django 5.2.13 on 2026-07-07 08:35

import django.db.models.deletion
import documents.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=180)),
                ('type_document', models.CharField(choices=[('rapport', 'Rapport'), ('note', 'Note'), ('courrier', 'Courrier'), ('procedure', 'Procédure'), ('administratif', 'Fichier administratif')], max_length=20)),
                ('fichier', models.FileField(upload_to=documents.models.document_upload_path)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('archive', 'Archivé')], default='actif', max_length=20)),
                ('est_archive', models.BooleanField(default=False)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_created', to=settings.AUTH_USER_MODEL)),
                ('service_concerne', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='accounts.service')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-date_ajout'],
            },
        ),
    ]
