# Generated by Django 5.2.13 on 2026-09-21 11:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="destinataires",
            field=models.ManyToManyField(
                blank=True,
                related_name="documents_recus",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Agents destinataires",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="pour_tous",
            field=models.BooleanField(
                default=False,
                help_text="Le document devient consultable par tous les comptes actifs.",
                verbose_name="Tous les agents de la DGES",
            ),
        ),
    ]
