# Generated by Django 5.2.13 on 2026-07-07 08:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=150)),
                ('contact', models.CharField(max_length=80)),
                ('provenance', models.CharField(blank=True, max_length=150)),
                ('motif', models.TextField()),
                ('heure_entree', models.DateTimeField(default=django.utils.timezone.now)),
                ('heure_sortie', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('present', 'Présent'), ('sorti', 'Sorti'), ('annule', 'Annulé')], default='present', max_length=20)),
                ('agent_visite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitors_received', to=settings.AUTH_USER_MODEL)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitors_created', to=settings.AUTH_USER_MODEL)),
                ('service_visite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitors', to='accounts.service')),
            ],
            options={
                'verbose_name': 'Visiteur',
                'verbose_name_plural': 'Visiteurs',
                'ordering': ['-heure_entree'],
            },
        ),
    ]
